[phases.setup]
nixPkgs = ["openjdk"]

[phases.build]
commands = [
    "javac src/game/server/GameServer.java src/game/server/*.java src/game/client/*.java src/game/common/*.java src/Main.java"
]

[start]
cmd = "java -cp src game.server.GameServer"